# .github/workflows/ci.yml

name: CI Pipeline for Cinscreve

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Atualizado para v4

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Atualizado para v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Frontend Dependencies
        run: cd frontend && npm install

      - name: Run Frontend Lint and Tests (se houver)
        run: cd frontend && npm run test

      - name: Build Frontend
        run: cd frontend && npm run build

      - name: Install Backend Dependencies
        run: cd backend && npm install

      - name: Run Backend Tests
        run: cd backend && npm test

      - name: Archive Frontend Build Artifact
        uses: actions/upload-artifact@v4 # 👈 Mude de v3 para v4 aqui
        with:
          name: frontend-build
          path: frontend/dist