# .github/workflows/ci.yml
name: CI Pipeline for Cinscreve

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # --- Etapas para o Backend ---
      - name: Setup Node.js (Backend)
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'

      - name: Install Backend Dependencies
        run: cd backend && npm install

      - name: Run Backend Unit Tests
        run: cd backend && npm test
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
          MONGO_URI_TEST: ${{ secrets.MONGO_URI_TEST }}
          EXTERNAL_AUTH_API_URL: ${{ secrets.EXTERNAL_AUTH_API_URL }}

      - name: Iniciar servidor backend
        run: |
          # Inicia o servidor em segundo plano e redireciona a saída para um arquivo de log
          npm start &
          # Espera um tempo para garantir que o servidor está totalmente operacional
          # Ajuste este tempo se necessário
          sleep 10
        working-directory: ./backend
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}

      # --- Etapas para o Frontend ---
      - name: Setup Node.js (Frontend)
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install Frontend Dependencies
        run: cd frontend && npm install

      - name: Build Frontend
        run: cd frontend && npm run build

      - name: Archive Frontend Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist

      - name: Parar servidor backend
        # Certifica-se de que o servidor é parado, mesmo se os testes falharem
        if: always()
        run: |
          echo "Parando o servidor backend..."
          kill $(lsof -t -i:3002) || true
